# Generated by Django 5.0.6 on 2024-05-21 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=14)),
                ('description', models.TextField()),
                ('direction', models.CharField(choices=[('Darslik', 'Darslik'), ("O'quv qo'llanma", "O'quv qo'llanma"), ('Monografiya', 'Monografiya'), ("Uslubiy qo'llanma", "Uslubiy qo'llanma"), ("Uslubiy ko'rsatma", "Uslubiy ko'rsatma")], max_length=50)),
                ('confirmed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file1', models.FileField(upload_to='books1/')),
                ('file2', models.FileField(upload_to='books2/')),
                ('file3', models.FileField(upload_to='books3/')),
                ('file4', models.FileField(upload_to='books4/')),
                ('file5', models.FileField(upload_to='books5/')),
            ],
        ),
        migrations.CreateModel(
            name='CheckBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.book')),
            ],
        ),
    ]
